### ISSUE TITLE
[Feature] Make `GroupLayer` a `LayerList` for rendering purposes?

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/napari-experimental#11]
**Is your feature request related to a problem? Please describe.**

We can likely obtain a large amount of functionality from having `GroupLayer` also be a `LayerList`, however the difficulty lies in the fact that we cannot edit the underlying napari core code, and our `GroupLayer` at current wraps `Layers` in `Node`s, which means a straight `LayerList` mixin won't work.

**Describe the solution you'd like**

The `GroupLayer` object should have the functionality of the current `LayerList` - toggles for visibility, relative reordering, etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by K-Meech** [comment]
Just a note that styling may be fixed as part of https://github.com/brainglobe/napari-experimental/issues/10 . In order to add a right click menu, I'm making a sub-class from `LayerDelegate` which brings a lot of functionality / styling with it.

**Comment by willGraham01** [comment]
As @K-Meech said above, this will be fixed with the implementation on `km/right-click` along with #10. Leaving open for now

**Comment by willGraham01** [comment]
Closing as implemented with #29 - we now inherit the `LayerDelegate` formatting
