### ISSUE TITLE
[Feature] Layers within the layer group list should be reorderable

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/napari-experimental#16]
**Is your feature request related to a problem? Please describe.**
The order of layers in the layer list matters, as it defines which layer is visualised above which in the canvas. The order can be changed by drag and drop action.

**Describe the solution you'd like**
The layer group list should behave like the layer list in this aspect, with the addition that one can drag and drop an entire group up and down the layer group list.

**Describe alternatives you've considered**

\

**Additional context**
Thanks to @Czaki for pointing this out at today's community meeting.

**Comment by willGraham01** [comment]
I've added this to the end of https://github.com/brainglobe/napari-experimental/issues/9, for now at least.

**Comment by alessandrofelder** [comment]
Duplicate of #9
