### ISSUE TITLE
[Feature] depend on napari `main`

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/napari-experimental#17]
**Is your feature request related to a problem? Please describe.**

`napari` 0.5 is close to release.

**Describe the solution you'd like**

This package should depend on the `main` branch of napari on GH, I think, so we avoid depending on obsolete API.

**Describe alternatives you've considered**

\

**Additional context**
Thanks to @Czaki for pointing this out at today's community meeting

**Comment by willGraham01** [comment]
It's probably not a good idea to depend on the HEAD of napari in general (if we ever release this plugin that might cause some problems), but I agree it would be good to have some tests running.

I've opened #18 which now lets us:
- Optionally install via `pip install .[napari-latest]`, which results in napari being fetched from the repo `main`.
- Adds a check in the CI that runs our tests with this optional install, IE with the latest changes to napari `main`. This will at least give us a warning if we're depending on any deprecated features!

**Comment by alessandrofelder** [comment]
Agree - the idea is to depend on napari >= 0.5 when it is released, which is expected to happen before we'd want to release this package

**Comment by willGraham01** [comment]
With #18 merged we are now effectively depending on napari `main` (CI will fail and warn us).

However let's leave this issue open so we know that once `napari 0.5` does come out, we should pin `napari >=0.5` in our main dependencies. Then we'll have tests running on the latest stable version of napari and the latest development version.

**Comment by willGraham01** [comment]
Update as of 9/7/2024; looks like napari 0.5 is _nearly_ there: https://github.com/napari/napari/milestone/36

**Comment by Czaki** [comment]
There are already pre releases of napari on pypi. You may depend on `napari>-0.5.0b0`.
