### ISSUE TITLE
[Feature] Allow group layer visibility to be changed with one click

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/napari-experimental#24]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to toggle group-wide visibility.

**Describe the solution you'd like**
Visibility toggle with one click on a eye icon. This should toggle visibility for all layers (including nested group layers) inside the group.

**Describe alternatives you've considered**

\

**Additional context**

\

**Comment by willGraham01** [comment]
Closing as implemented in #30 :partying_face:
