### ISSUE TITLE
[Feature] Allow renaming of `GroupLayer`s and `NodeWrappingLayer` when double clicked

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/napari-experimental#5]
**Is your feature request related to a problem? Please describe.**

When the user double clicks on an item in the list in the GroupLayerWidget, a text box appears prompting a new name. This is not currently set to the selected object upon confirmation.

**Describe the solution you'd like**

The new name should be set for 
- [x] `GroupLayer`s (KM)
- [x] `NodeWrappingLayer`s (WG)

and reflected in the UI

**Describe alternatives you've considered**

**Additional context**

**Comment by K-Meech** [comment]
Working on `ARC-dev-branch`, so I'll close this now
