### ISSUE TITLE
[Feature] Setup some documentation!

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/napari-experimental#8]
**Is your feature request related to a problem? Please describe.**

We should document how the widget works, as we are writing it.

**Describe the solution you'd like**

- [ ] README with overall ethos, structure, important classes, and ideas for organisation.
- [ ] Docstrings for all public-facing methods and non-intuitive private methods.
- [ ] Tests, where not obviously named, should also have docstrings.

**Describe alternatives you've considered**

**Additional context**

**Comment by K-Meech** [comment]
We should make sure all docstrings use `numpydoc` style - this is what both Napari and Brainglobe use. (currently there are some reST style docstrings)

**Comment by willGraham01** [comment]
README needs an infodump. We should probably have the following sections:

- Overview
  - What this plugin does?
  - Ethos (it's an entirely separate way to interact with layers, do not use the other viewer except for adding layers)
  - Outlook - hopefully this plugin widget will just replace the existing layerlist viewer instance
- Implementation details
  - Key classes (`GroupLayerNode`, `GroupLayer`, and the QT things)
  - Our use and subclassing of Group and Node
  - Explain the decision to not make `Layer`s into a `Node` subclass, but instead to track pointers to them
  - Indexing and fun times
  - Event propagation (down the tree)
  - The debugger entry is still there
- Todo
  - Desirable features
  - Known bugs and issues (non-breaking but poor UX)
  - Known bugs and issues (breaking)

**Comment by K-Meech** [comment]
I'll start writing the `Overview` + `Todo` sections for the README

**Comment by willGraham01** [comment]
I'll start tackling the `Implementation` section now

**Comment by willGraham01** [comment]
We now have each of the requested items in the issue list present in the repository. Going to close this issue now, but in future we might want to look into a docs build if the plugin gets a lot bigger than it currently is.
